version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      # . に package.json などがある想定
      - ./:/workspace

      # node_modulesを名前付きボリュームに隠す
      - front_node_modules:/workspace/node_modules

volumes:
  front_node_modules:
  #   depends_on:
  #     - backend
  # backend:
  #   build: ./backend
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./backend:/app