version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      # . に package.json などがある想定
      - ./frontend/:/app

      # node_modulesを名前付きボリュームに隠す
      - front_node_modules:/app/node_modules
    depends_on:
      - backend
    entrypoint: >
      sh -c "
       npm i &&
        docker-entrypoint.sh npm run start \
         --character-set-server=utf8mb4 \
          --collation-server=utf8mb4_unicode_ci
      "
    networks:
      - pasty
    links:
      - backend
      
  backend:
    container_name: "pasty_backend"
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    entrypoint: >
      sh -c "
       pip install -r requirements.txt &&
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "
    networks:
      - pasty

volumes:
  front_node_modules:

networks:
  pasty:
    driver: bridge