version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      # . に package.json などがある想定
      - ./frontend/:/app

      # node_modulesを名前付きボリュームに隠す
      - front_node_modules:/app/node_modules
    depends_on:
      - backend
      
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

volumes:
  front_node_modules:

  